### ISSUE TITLE
error

### ISSUE THREAD

**Issue by weigq** [hezhangsprinter/ID-CGAN#1]
hi, 
I just follow the instructions you give, but I encounter the following error:

```
@imcl-test:/ID-CGAN/IDCGAN$ DATA_ROOT=./datasets/rain name=rain which_direction=BtoA th train.lua

Found Environment variable CUDNN_PATH = /data/XXX/cuda/lib64/libcudnn.so.5.1.10	

/data/XXX/torch/install/bin/luajit: cannot open <per_loss/models/vgg16.t7> in mode r  at /data/XXX/torch/pkg/torch/lib/TH/THDiskFile.c:670

stack traceback:
	[C]: at 0x7f52554e1ad0
	[C]: in function 'DiskFile'
	/data/XXX/torch/install/share/lua/5.1/torch/File.lua:405: in function 'load'
	train.lua:68: in main chunk
	[C]: in function 'dofile'
	...eigq/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:145: in main chunk
	[C]: at 0x00406670

```

can you help me? @hezhangsprinter 
thanks

**Comment by hezhangsprinter** [comment]
Hi,
   You may look at the solution for this issue. https://github.com/facebookresearch/deepmask/issues/8
But I am not sure whether you can fix it or not.  

But I do recommend you to run (https://github.com/phillipi/pix2pix) first. 

![image](https://cloud.githubusercontent.com/assets/24211607/23337281/65688d00-fbb6-11e6-832c-819e4d03405b.png)
