### ISSUE TITLE
the trained discriminator

### ISSUE THREAD

**Issue by xinario** [hezhangsprinter/ID-CGAN#2]
Can you please also share your trained discriminator? 

I saw that in the configuration file, the number of iteration is set to be 2000. I'm wondering if that is necessary to achieve your performance.

**Comment by hezhangsprinter** [comment]
Hi,
    It is not necessary to train 2000 epochs .  I remembered that 500 or 600 epochs should be enough.  
    I try to find the trained discriminator and it may take some time. As I never use it during the testing,  I will message once I find it.

**Comment by mohanrajmit** [comment]
Can I also get the trained discriminator for test code.
