### ISSUE TITLE
quantitative measures

### ISSUE THREAD

**Issue by lizhuorong** [hezhangsprinter/ID-CGAN#3]
Are you agree that PSNR, SSIM, UQI and VIF are reasonable quantitative metrics for synthetic images? Would you please release the evaluation implementation including the comparison with the baselines? Thanks a lot : )

**Comment by hezhangsprinter** [comment]
HI,
    It will be hard to say whether those quantitative metrics are the best measurement to refect the image quality. But they are reasonable quantitative metrics that can reflect the image quality.  So, you mean you want to ask for my evaluation code ?
