### ISSUE TITLE
Quality measures in source code

### ISSUE THREAD

**Issue by TrinhQuocNguyen** [hezhangsprinter/ID-CGAN#4]
At first, thank you for your awesome source code and it ran perfectly like you said in the paper.

I read your paper and source code, but can not found any places in the source code which were implemented and showed the quality measures as "Peak Signal to Noise Ratio (PSNR), Structural Similarity Index (SSIM) [48], Universal Quality Index (UQI) [49] and Visual Information Fidelity (VIF)[50]" in the paper.

Could you please show me where and how did you evaluate these criteria. 
Thanks in advance.

**Comment by hezhangsprinter** [comment]
Hi 
   I don't have the evaluation metrics in my released code. I think you can find the corresponding evaluation metric here.  
Basically, just save all the result to jpg and run the quantitative evaluation methods.
I use the code from this github page: 
https://github.com/sattarab/image-quality-tools

**Comment by TrinhQuocNguyen** [comment]
Thank you for a lovely tool and your support. 
I am digging into your source code now, I wonder that whether your code can be added more LSTM layers to de-rain in raining videos or to de-raindrops in videos which is captured under the raining condition.
You probably can publish another paper for that.

Thank you again for your support.

**Comment by hezhangsprinter** [comment]
Yeah, That can be a possible extended version. Thanks for the advice.

**Comment by TrinhQuocNguyen** [comment]
Hi Hezhangsprinter, 
I have seen the config:
>>>>serial_batches = 1,       -- if 1, takes images in order to make batches, otherwise takes them randomly

I have set serial_batches = 1 in train and test files, but they still get randomly image to test (or train). Could you please show me how to modify to make model gets the images sequentially

Thanks in advance.

**Comment by hezhangsprinter** [comment]
Hi
   Can you remind me after Nov.15th?
But I am a little busy recently.
I remember that my testing code generate the  the images sequentially

Best,
He Zhang

**Comment by TrinhQuocNguyen** [comment]
Hi He Zhang ,
Have you checked the source code for rendering the images sequentially.
I did go through your source code, but did not find any place to change it. It's probably in dataset.lua file, somewhere at getBatch() function.
Thanks
