### ISSUE TITLE
Image will be resize to a square

### ISSUE THREAD

**Issue by stevewongv** [hezhangsprinter/ID-CGAN#5]
Could test images remind origenal shape? or I need to resize them to regular shape?

**Comment by hezhangsprinter** [comment]
Hi
   Sorry for the late reply. You have to the data-loader and  pre-processing to use the original size  of the input image.

**Comment by stevewongv** [comment]
Thank you for your reply!
I tried to  revise the code but failed since I am not familiar with Lua. Can you give me more information about the code where I need to modify?

**Comment by TrinhQuocNguyen** [comment]
Hi TioWang, 
You can pre-processing the image first to convert it into square and after get the result from model, you can convert back to the size you want using Opencv. Since Lua currently only supports on Opencv 3.1, You can only use Opencv 3.1.

**Comment by stevewongv** [comment]
But I think this will reduce the image quality, right?

**Comment by TrinhQuocNguyen** [comment]
Apparently, It is. Or you can modify the code to make it processes on Size(width, height) as you want.
