### ISSUE TITLE
dataset

### ISSUE THREAD

**Issue by suke27** [hezhangsprinter/ID-CGAN#6]
Hi, seems I can not access the dataset url, could you share dataset by other method？ thank you!

**Comment by hezhangsprinter** [comment]
Hi
   Hmm. If you cannot access to google then you may be also not able to
access to dropbox.

Do you have any baidu yunpan that I can upload? I don't have any baidu
account now.

Best,
He Zhang

**Comment by suke27** [comment]
Thank you for reply, I have downloaded the dataset, but I found it is not nature rainy image, it is fake image. I  think it may influence the result, do you try using other images

**Comment by hezhangsprinter** [comment]
Hi
    I train using synthetic samples and the method generalize well to real
world images. The real world testing images are also in the google drive
link.
