### ISSUE TITLE
Deraining errors on CPU machine

### ISSUE THREAD

**Issue by mohanrajmit** [hezhangsprinter/ID-CGAN#8]
Hi,

I am trying to run this code in ubuntu without GPU.
I am facing some issues. please find the below errors.

![image](https://user-images.githubusercontent.com/9213878/39180048-e1ee1e02-4783-11e8-8096-96b9f0255ecc.png)

**Comment by hezhangsprinter** [comment]
Hi There, 
     You may need to check how torch work on CPU and also uncomment any codes with cudnn. If you need some results from the code. I may be able to run for you. 

Best

**Comment by mohanrajmit** [comment]
Thanks for your reply.

Can you please help me to run the code in CPU.

Thanks,
Mohan

**Comment by hezhangsprinter** [comment]
Sorry there,
       I couldn't help at this point. I highly recommend you go through the Torch documentation.
